export default {
  checkers: ["typescript"],
  coverageAnalysis: "perTest",
  mutate: [
    "packages/turn-fold/compaction-visibility.ts",
    "packages/turn-fold/configuration.ts",
    "packages/turn-fold/edit-diff-stat.ts",
    "packages/turn-fold/fold-policy.ts",
    "packages/turn-fold/history-entry.ts",
    "packages/turn-fold/history-index.ts",
    "packages/turn-fold/history-input.ts",
    "packages/turn-fold/history-navigation.ts",
    "packages/turn-fold/history-renderer.ts",
    "packages/turn-fold/history-scope.ts",
    "packages/turn-fold/history-search.ts",
    "packages/turn-fold/history-viewport.ts",
    "packages/turn-fold/projection-plan.ts",
    "packages/turn-fold/restart-marker.ts",
    "packages/turn-fold/transcript-window-adapter.ts",
    "packages/turn-fold/transcript-windows.ts",
    "packages/turn-fold/tool-padding.ts",
    "packages/turn-fold/turn-visibility.ts",
    "packages/live-stats/live-stats.ts",
    "packages/nyan-mode/src/cost.ts",
    "packages/nyan-mode/src/png.ts",
    "packages/nyan-mode/src/progress.ts",
    "packages/prompt-queue/queue-model.ts",
    "packages/prompt-queue/history-model.ts",
    "packages/prompt-queue/delivery-policy.ts",
    "packages/prompt-queue/submit-policy.ts",
    "packages/prompt-queue/message-text.ts",
    "packages/prompt-queue/widget-lines.ts",
    "packages/prompt-queue/window-state.ts",
    "packages/reliable-compaction/reliable-compaction.ts",
    "packages/context-window-policy/context-window-policy.ts",
    "packages/startup-model/startup-model.ts",
    "packages/codex-usage/src/codex-usage.ts",
    "packages/codex-usage/src/format.ts",
    "packages/codex-usage/src/normalize.ts",
    "packages/plan-checklist/plan-context.ts",
    "packages/plan-checklist/plan-render.ts",
    "packages/plan-checklist/plan-replay.ts",
    "packages/plan-checklist/plan-schema.ts",
    "packages/plan-checklist/plan-state.ts",
    "packages/unified-exec/src/completion.ts",
    "packages/unified-exec/src/format-time.ts",
    "packages/unified-exec/src/head-tail-buffer.ts",
    "packages/unified-exec/src/time.ts",
    "packages/unified-exec/src/unescape.ts",
    "packages/yarp/index.ts",
    "packages/pi-reviewer/src/args.ts",
    "packages/pi-reviewer/src/config.ts",
    "packages/pi-reviewer/src/git-target.ts",
    "packages/pi-reviewer/src/pi-events.ts",
    "packages/pi-reviewer/src/review-output.ts",
    "packages/pi-reviewer/extensions/shell-policy.ts",
  ],
  reporters: ["clear-text", "progress"],
  testRunner: "vitest",
  thresholds: {
    break: 85,
    high: 90,
    low: 85,
  },
  tsconfigFile: "tsconfig.json",
};
