export default {
  checkers: ["typescript"],
  coverageAnalysis: "perTest",
  mutate: [
    "packages/turn-fold/configuration.ts",
    "packages/turn-fold/fold-policy.ts",
    "packages/turn-fold/mode.ts",
    "packages/turn-fold/transcript-window-adapter.ts",
    "packages/turn-fold/transcript-windows.ts",
    "packages/turn-fold/tool-padding.ts",
    "packages/live-stats/live-stats.ts",
    "packages/nyan-mode/src/cost.ts",
    "packages/nyan-mode/src/png.ts",
    "packages/nyan-mode/src/progress.ts",
    "packages/prompt-queue/queue-model.ts",
    "packages/prompt-queue/history-model.ts",
    "packages/prompt-queue/delivery-policy.ts",
    "packages/prompt-queue/submit-policy.ts",
    "packages/prompt-queue/message-text.ts",
    "packages/prompt-queue/widget-lines.ts",
    "packages/prompt-queue/window-state.ts",
    "packages/reliable-compaction/reliable-compaction.ts",
    "packages/context-window-policy/context-window-policy.ts",
    "packages/plan-checklist/plan-context.ts",
    "packages/plan-checklist/plan-render.ts",
    "packages/plan-checklist/plan-replay.ts",
    "packages/plan-checklist/plan-schema.ts",
    "packages/plan-checklist/plan-state.ts",
    "packages/shell-execution-policy/shell-execution-policy.ts",
  ],
  reporters: ["clear-text", "progress"],
  testRunner: "vitest",
  thresholds: {
    break: 85,
    high: 90,
    low: 85,
  },
  tsconfigFile: "tsconfig.json",
};
