export default {
  checkers: ["typescript"],
  coverageAnalysis: "perTest",
  mutate: [
    "packages/turn-fold/fold-policy.ts",
    "packages/turn-fold/mode.ts",
    "packages/turn-fold/output-metrics.ts",
    "packages/pi-tui-history-replay/history-replay.ts",
    "packages/live-stats/live-stats.ts",
    "packages/prompt-queue/queue-model.ts",
    "packages/prompt-queue/history-model.ts",
    "packages/prompt-queue/delivery-policy.ts",
    "packages/prompt-queue/submit-policy.ts",
    "packages/prompt-queue/message-text.ts",
    "packages/prompt-queue/widget-lines.ts",
    "packages/prompt-queue/window-state.ts",
  ],
  reporters: ["clear-text", "progress"],
  testRunner: "vitest",
  thresholds: {
    break: 85,
    high: 90,
    low: 85,
  },
  tsconfigFile: "tsconfig.json",
};
