import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    coverage: {
      include: [
        "packages/command-guard/src/adapters.ts",
        "packages/command-guard/src/decision.ts",
        "packages/command-guard/src/execution-check.ts",
        "packages/command-guard/src/bash-parser.ts",
        "packages/command-guard/src/classifier.ts",
        "packages/command-guard/src/contexts.ts",
        "packages/command-guard/src/events.ts",
        "packages/command-guard/src/lexical.ts",
        "packages/command-guard/src/limits.ts",
        "packages/command-guard/src/path-policy.ts",
        "packages/command-guard/src/policy.ts",
        "packages/command-guard/src/powershell-parser.ts",
        "packages/command-guard/src/rsync.ts",
        "packages/command-guard/src/shell.ts",
        "packages/command-guard/src/tool-calls.ts",
        "packages/command-guard/src/unified-adapter.ts",
        "packages/turn-fold/configuration.ts",
        "packages/turn-fold/edit-diff-stat.ts",
        "packages/turn-fold/ephemeral-compactions.ts",
        "packages/turn-fold/fold-policy.ts",
        "packages/turn-fold/mode.ts",
        "packages/turn-fold/run-boundary.ts",
        "packages/turn-fold/transcript-window-adapter.ts",
        "packages/turn-fold/transcript-windows.ts",
        "packages/turn-fold/turn-message.ts",
        "packages/turn-fold/turn-state.ts",
        "packages/turn-fold/tool-padding.ts",
        "packages/goal/goal-episode.ts",
        "packages/goal/goal-replay.ts",
        "packages/goal/goal-state.ts",
        "packages/goal/run-outcome.ts",
        "packages/goal/usage.ts",
        "packages/loop-guard/feature-encoder.ts",
        "packages/loop-guard/intervention-message.ts",
        "packages/loop-guard/loop-detector.ts",
        "packages/loop-guard/loop-guard-controller.ts",
        "packages/loop-guard/thinking-stream-detector.ts",
        "packages/live-stats/live-stats.ts",
        "packages/live-stats/working-phrases.ts",
        "packages/skill-slug/index.ts",
        "packages/nyan-mode/src/cat-state.ts",
        "packages/nyan-mode/src/cost.ts",
        "packages/nyan-mode/src/image.ts",
        "packages/nyan-mode/src/kitty-probe.ts",
        "packages/nyan-mode/src/layout.ts",
        "packages/nyan-mode/src/painter.ts",
        "packages/nyan-mode/src/png.ts",
        "packages/nyan-mode/src/progress.ts",
        "packages/nyan-mode/src/text-painter.ts",
        "packages/nyan-mode/src/text-runway.ts",
        "packages/nyan-mode/src/xpm.ts",
        "packages/prompt-queue/queue-model.ts",
        "packages/prompt-queue/history-model.ts",
        "packages/prompt-queue/delivery-policy.ts",
        "packages/prompt-queue/submit-policy.ts",
        "packages/prompt-queue/message-text.ts",
        "packages/prompt-queue/widget-lines.ts",
        "packages/prompt-queue/window-state.ts",
        "packages/reliable-compaction/reliable-compaction.ts",
        "packages/codex-switcher/codex-family.ts",
        "packages/codex-switcher/config.ts",
        "packages/codex-switcher/native-provider.ts",
        "packages/codex-switcher/router.ts",
        "packages/codex-switcher/usage-client.ts",
        "packages/codex-switcher/usage-policy.ts",
        "packages/pi-codex-compaction/codex-compaction.ts",
        "packages/pi-codex-compaction/native-checkpoint.ts",
        "packages/pi-codex-compaction/remote-compaction.ts",
        "packages/pi-codex-compaction/responses-input.ts",
        "packages/infinite-retry/infinite-retry.ts",
        "packages/onur-openclaw-maintainer/maintainer.ts",
        "packages/onur-openclaw-maintainer/openclaw-maintainer.workflow.ts",
        "packages/pi-usage/src/core.ts",
        "packages/pi-usage/src/format.ts",
        "packages/pi-usage/src/query.ts",
        "packages/pi-usage/src/usage.ts",
        "packages/pi-usage/src/providers/codex.ts",
        "packages/pi-usage/src/providers/github-copilot.ts",
        "packages/pi-usage/src/providers/openrouter.ts",
        "packages/pi-tui-kit/src/custom-interaction.ts",
        "packages/pi-tui-kit/src/interaction.ts",
        "packages/pi-tui-kit/src/model.ts",
        "packages/pi-tui-kit/src/navigator.ts",
        "packages/pi-tui-kit/src/runtime.ts",
        "packages/pi-tui-kit/src/task.ts",
        "packages/pi-tui-kit/src/components/rendering.ts",
        "packages/pi-tui-kit/src/components/review.ts",
        "packages/plan-checklist/plan-context.ts",
        "packages/plan-checklist/plan-render.ts",
        "packages/plan-checklist/plan-replay.ts",
        "packages/plan-checklist/plan-schema.ts",
        "packages/plan-checklist/plan-state.ts",
        "packages/unified-exec/src/collect.ts",
        "packages/unified-exec/src/command-environment.ts",
        "packages/unified-exec/src/command-input.ts",
        "packages/unified-exec/src/command-policy.ts",
        "packages/unified-exec/src/command-shell.ts",
        "packages/unified-exec/src/completion.ts",
        "packages/unified-exec/src/constants.ts",
        "packages/unified-exec/src/format-time.ts",
        "packages/unified-exec/src/head-tail-buffer.ts",
        "packages/unified-exec/src/long-wait.ts",
        "packages/unified-exec/src/notify.ts",
        "packages/unified-exec/src/session-store.ts",
        "packages/unified-exec/src/shell.ts",
        "packages/unified-exec/src/termination.ts",
        "packages/unified-exec/src/time.ts",
        "packages/unified-exec/src/tool-helpers.ts",
        "packages/unified-exec/src/unescape.ts",
        "packages/unified-exec/src/write-stdin.ts",
      ],
      provider: "v8",
      reporter: ["text", "json", "json-summary"],
      thresholds: {
        branches: 85,
        functions: 85,
        lines: 85,
        statements: 85,
      },
    },
    include: ["packages/**/*.test.ts"],
  },
});
