import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    coverage: {
      include: [
        "packages/turn-fold/configuration.ts",
        "packages/turn-fold/edit-diff-stat.ts",
        "packages/turn-fold/ephemeral-compactions.ts",
        "packages/turn-fold/fold-policy.ts",
        "packages/turn-fold/mode.ts",
        "packages/turn-fold/transcript-window-adapter.ts",
        "packages/turn-fold/transcript-windows.ts",
        "packages/turn-fold/turn-message.ts",
        "packages/turn-fold/turn-state.ts",
        "packages/turn-fold/tool-padding.ts",
        "packages/live-stats/live-stats.ts",
        "packages/live-stats/working-phrases.ts",
        "packages/nyan-mode/src/cat-state.ts",
        "packages/nyan-mode/src/cost.ts",
        "packages/nyan-mode/src/image.ts",
        "packages/nyan-mode/src/kitty-probe.ts",
        "packages/nyan-mode/src/layout.ts",
        "packages/nyan-mode/src/painter.ts",
        "packages/nyan-mode/src/png.ts",
        "packages/nyan-mode/src/progress.ts",
        "packages/nyan-mode/src/text-painter.ts",
        "packages/nyan-mode/src/text-runway.ts",
        "packages/nyan-mode/src/xpm.ts",
        "packages/prompt-queue/queue-model.ts",
        "packages/prompt-queue/history-model.ts",
        "packages/prompt-queue/delivery-policy.ts",
        "packages/prompt-queue/submit-policy.ts",
        "packages/prompt-queue/message-text.ts",
        "packages/prompt-queue/widget-lines.ts",
        "packages/prompt-queue/window-state.ts",
        "packages/reliable-compaction/reliable-compaction.ts",
        "packages/context-window-policy/context-window-policy.ts",
        "packages/codex-usage/src/codex-usage.ts",
        "packages/codex-usage/src/format.ts",
        "packages/codex-usage/src/normalize.ts",
        "packages/codex-usage/src/usage-service.ts",
        "packages/codex-usage/src/weekly-status.ts",
        "packages/plan-checklist/plan-context.ts",
        "packages/plan-checklist/plan-render.ts",
        "packages/plan-checklist/plan-replay.ts",
        "packages/plan-checklist/plan-schema.ts",
        "packages/plan-checklist/plan-state.ts",
        "packages/unified-exec/src/collect.ts",
        "packages/unified-exec/src/completion.ts",
        "packages/unified-exec/src/constants.ts",
        "packages/unified-exec/src/format-time.ts",
        "packages/unified-exec/src/head-tail-buffer.ts",
        "packages/unified-exec/src/long-wait.ts",
        "packages/unified-exec/src/notify.ts",
        "packages/unified-exec/src/session-store.ts",
        "packages/unified-exec/src/shell.ts",
        "packages/unified-exec/src/termination.ts",
        "packages/unified-exec/src/time.ts",
        "packages/unified-exec/src/tool-helpers.ts",
        "packages/unified-exec/src/unescape.ts",
        "packages/unified-exec/src/write-stdin.ts",
      ],
      provider: "v8",
      reporter: ["text", "json", "json-summary"],
      thresholds: {
        branches: 85,
        functions: 85,
        lines: 85,
        statements: 85,
      },
    },
    include: ["packages/**/*.test.ts"],
  },
});
