import assert from "node:assert/strict";
import { test } from "vitest";
import { rules } from "../rules.ts";

const cases: Array<[string, string, number, number[]?]> = [
  ["no-chain", "No sign-ups, no downloads, no hassle — just paste and go.", 1, [3]],
  ["no-chain", "The plan has no hidden fees and no long-term contracts.", 1, [2]],
  ["no-chain", "No fluff, no filler, no jargon, no corporate buzzwords.", 1, [4]],
  ["no-chain", "There is no catch here, honestly.", 0, []],
  ["no-chain", "It ships with no bells and whistles, no fluff.", 1, [2]],
  ["no-chain", "No, no, I insist.", 0, []],
  ["no-chain", "no no no", 0, []],
  ["no-chain", "with no list patterns at all, so nothing lights up.", 0, []],
  ["no-chain", "NO FEES, NO CONTRACTS, NO SURPRISES", 1, [3]],
  ["no-chain", "no fluff; no filler", 1, [2]],
  ["no-chain", "no time, no money, no way to say no thanks", 1, [3]],
  ["no-chain", "no-code, no-fuss setup", 1, [2]],
  ["no-chain", "I know nothing, notice nothing.", 0, []],
  ["no-chain", "No fluff, no filler.\nNo ads here.", 1, [2]],
  ["whole", "That's the whole point.", 1],
  ["whole", "This is the whole game, really.", 1],
  ["whole", "That was the whole pitch.", 1],
  ["whole", "The whole team showed up.", 0],
  ["did-not-chain", "Did not flinch, did not blink, did not apologize.", 1, [3]],
  ["did-not-chain", "He didn't call and didn't write.", 1, [2]],
  ["did-not-chain", "She did not go.", 0, []],
  ["did-not-chain", "Did not know why, did not care.", 1, [2]],
  ["dont-verb-it", "Don't call it a comeback. Call it a return.", 1],
  ["dont-verb-it", "Do not think of it as a burden. Think of it as fuel.", 1],
  ["dont-verb-it", "Don't fear it. Name it.", 0],
  ["dont-verb-it", 'Don\u2019t call it "luck." Call it preparation.', 1],
  ["dont-verb-it", "Don't just read it — read it aloud.", 1],
  ["dont-verb-it", "Don't overthink it.", 0],
  ["sit-with", "Sit with that for a moment.", 1],
  ["sit-with", "Just sit with it.", 1],
  ["sit-with", "She was sitting with the discomfort.", 1],
  ["sit-with", "Come sit with us at lunch.", 0],
  ["already-know", "You already know the answer.", 1],
  ["already-know", "Deep down, you already know.", 1],
  ["already-know", "If you already know Python, skip ahead.", 0],
  ["already-know", "You already know what to do.", 1],
  ["already-know", "Part of you already knows it.", 1],
  ["is-the-entire", "Consistency is the entire game.", 1],
  ["is-the-entire", "That's the entire business model.", 1],
  ["is-the-entire", "He toured the entire factory.", 0],
  ["the-entire-is", "The entire point is that nobody reads.", 1],
  ["the-entire-is", "The entire business model is built on churn.", 1],
  ["the-entire-is", "The entire point of the exercise is repetition.", 1],
  ["the-entire-is", "He ate the entire pizza.", 0],
  ["the-entire-is", "The entire team was exhausted.", 1],
  ["the-entire-is", "The entire history of the modern industrial world economy is complex.", 0],
  ["is-real", "The improvement is real, and it's not subtle.", 1],
  ["is-real", "This is the real work, and it never ends.", 1],
  ["is-real", "The demand is real and growing.", 1],
  ["is-real", "He is a real estate agent and it shows.", 0],
  ["is-real", "Is it real? And does it matter?", 0],
  ["is-real", "The painting is real, but stolen.", 0],
  ["punchline", "The punchline is that nobody laughed.", 1],
  ["punchline", "The punchline: nothing changed.", 1],
  ["punchline", "And the punchline? You knew.", 1],
  ["punchline", "He forgot the punchline entirely.", 0],
  ["worth-naming", "That loss is real and it's worth naming.", 1],
  ["worth-naming", "It’s worth naming that this hurts.", 1],
  ["worth-naming", "The grief here is worth naming.", 1],
  ["worth-naming", "That anger feels worth naming out loud.", 1],
  ["worth-naming", "Worth naming: nobody asked for this.", 1],
  ["worth-naming", "It's not worth naming names here.", 0],
  ["worth-naming", "They spent the meeting naming the new mascot.", 0],
  ["worth-naming", "The naming convention is worth documenting.", 0],
  ["not-nothing", "That's not nothing.", 1],
  ["not-nothing", "Ten sign-ups in a week — that is not nothing.", 1],
  ["not-nothing", "It's not nothing, even if it's not everything.", 1],
  ["not-nothing", "The launch drew a small crowd, which was not nothing.", 1],
  ["not-nothing", "She insisted that nothing was wrong.", 0],
  ["not-nothing", "There is nothing left to say.", 0],
  ["is-the-whole", "Distribution is the whole game.", 1],
  ["is-the-whole", "Here's the whole pitch in one slide.", 1],
  ["is-the-whole", "That was the whole point of the meeting.", 1],
  ["is-the-whole", "The whole team showed up.", 0],
  [
    "echo-triad",
    "A shopping cart is an object in the system. A chat room is an object in the system.",
    1,
    [2],
  ],
  [
    "echo-triad",
    "The parser is a state machine. The renderer is a state machine. The scheduler is a state machine.",
    1,
    [3],
  ],
  ["echo-triad", "The parser is fast today. The renderer is fast today.", 0, []],
  ["echo-triad", "The parser is fast. The tests are slow.", 0, []],
  ["performative-honesty", "I won't pretend the migration was painless.", 1],
  ["performative-honesty", "Let's be honest: nobody reads the docs.", 1],
  ["performative-honesty", "To be clear, the API is unchanged.", 1],
  ["performative-honesty", "Honestly, it was fine.", 1],
  ["performative-honesty", "She answered honestly.", 0],
  ["performative-honesty", "Look at the diagram.", 0],
  ["thats-the-part", "That's the part a counter can't reach.", 1],
  ["thats-the-part", "The part that makes me trust the rest is the errata.", 1],
  ["thats-the-part", "My favorite part of the demo was the undo.", 1],
  ["thats-the-part", "He played the part of the villain.", 0],
  ["the-only-i-trust", "It’s the only marketing I trust.", 1],
  ["the-only-i-trust", "The only benchmark that matters is retention.", 1],
  ["the-only-i-trust", "The only thing it needs is a cache.", 1],
  ["the-only-i-trust", "She was the only engineer on call.", 0],
  ["take-my-word", "You don't have to take my word for it.", 1],
  ["take-my-word", "Don't take my word for any of this.", 1],
  ["take-my-word", "He kept his word.", 0],
  ["turns-out", "Turns out the cache was never warm.", 1],
  ["turns-out", "It turns out that nobody tested it.", 1],
  ["turns-out", "She turns out solid work every week.", 0],
  ["fits-in-your-head", "The design is small enough to hold in your head.", 1],
  ["fits-in-your-head", "It ships with sane defaults and zero config.", 2],
  ["fits-in-your-head", "Install it and it just works.", 1],
  ["fits-in-your-head", "We choose boring technology on purpose.", 0],
  ["fits-in-your-head", "The helmet fits your head.", 0],
  ["stacked-questions", "Do I know how it works? Where it breaks? Which corners it cut?", 1, [3]],
  ["stacked-questions", "Was it worth it? Would I do it again?", 1, [2]],
  ["stacked-questions", "Did it work? Yes, and then some.", 0, []],
  ["stacked-questions", "What changed?", 0, []],
  ["sentence-anaphora", "Maybe nobody needed it. Maybe the timing was off. Maybe both.", 1, [3]],
  ["sentence-anaphora", "Maybe nobody needed it. Maybe the timing was off.", 0, []],
  [
    "sentence-anaphora",
    "The parser is small. The renderer is small. The scheduler is small.",
    1,
    [3],
  ],
  [
    "sentence-anaphora",
    "Everything changed. Everything slowed down. Everything cost more.",
    1,
    [3],
  ],
  ["emoji-heading", "## \u{1F680} Deploy notes", 1],
  ["emoji-heading", "- \u{1F389} Ship it", 1],
  ["emoji-heading", "1. \u{1F4E6} Package it", 1],
  // The finder also fires on a plain line that opens with an emoji, which is
  // wider than the rule description says. Pinned so the difference shows.
  ["emoji-heading", "\u{1F680} Party time", 1],
  ["emoji-heading", "## \u{1F680}", 0],
  ["emoji-heading", "Ship it with \u{1F680} inside the line.", 0],
  [
    "colon-triple",
    "The fix needs three things: separate ports, separate processes, and separate state.",
    1,
  ],
  ["colon-triple", "Each service gets its own everything: ports, processes, local state.", 1],
  ["colon-triple", "The recipe calls for flour, butter, and sugar.", 0],
  ["colon-triple", "Note: the flag is off by default.", 0],
  ["heres-the-twist", "Here's the twist: nobody clicked it.", 1],
  ["heres-the-twist", "Here is the thing. The demo was fake.", 1],
  ["heres-the-twist", "Here's a surprising result: it got faster.", 1],
  ["heres-the-twist", "Here's the door code.", 0],
  ["x-is-dead", "Peer code review is dead.", 1],
  ["x-is-dead", "The old importer is dead; long live the importer.", 2],
  ["x-is-dead", "Long live the king.", 1],
  ["x-is-dead", "He played dead until the bear left.", 0],
  ["thats-why-mattered", "That's why being able to open the environment mattered.", 1],
  ["thats-why-mattered", "This is why preserving every conversation mattered.", 1],
  ["thats-why-mattered", "That's why the deadline counts.", 1],
  ["thats-why-mattered", "That is why we left early.", 0],
  ["stranded-auxiliary", "The tool died; the data didn't.", 1],
  ["stranded-auxiliary", "Reading mostly passed, writing didn't.", 1],
  ["stranded-auxiliary", "Maybe it wouldn't have.", 1],
  ["stranded-auxiliary", "The test passed and the build was green.", 0],
  ["ai-vocab", "We delve into the intricacies of the interplay.", 3],
  ["ai-vocab", "Her vibrant tapestry hung in the bustling hall.", 3],
  ["ai-vocab", "A meticulously curated, seamless experience.", 2],
  ["ai-vocab", "The report was thorough and well organized.", 0],
  ["vocab-rare", "The re-derived, mutation-verified output was byte-identical.", 3],
  ["vocab-rare", "Was it honestly re-measured after the pre-fix state?", 2],
  ["vocab-rare", "The load-bearing pipeline is re-verified bit-identical.", 3],
  ["vocab-rare", "Honestly, the build was green all along.", 1],
  ["vocab-rare", "We reported the results honestly to the client.", 0],
  ["vocab-stance", "The fix is provably correct and empirically sound.", 2],
  ["vocab-stance", "The result was structurally inevitable.", 1],
  ["vocab-stance", "He quoted the terms verbatim.", 1],
  ["vocab-stance", "The change is correct and works in practice.", 0],
  ["vocab-epistemic", "The premise was refuted, and the verdict stands.", 3],
  ["vocab-epistemic", "She asserted the asymmetry was falsified.", 3],
  ["vocab-epistemic", "The author refuses to concede the contradiction.", 1],
  ["vocab-epistemic", "We refused the delivery and assert our rights.", 1],
  ["vocab-epistemic", "The meeting was about planning.", 0],
  ["vocab-metaphor", "The seam between the modules is a real wedge.", 2],
  ["vocab-metaphor", "The whole machinery feels inert and latent.", 3],
  ["vocab-metaphor", "A backstop against regressions.", 1],
  ["vocab-metaphor", "The phantom fix was a throwaway.", 2],
  ["vocab-metaphor", "The machine seamed the fabric neatly.", 0],
  ["vocab-survival", "The claim survived the review, restated plainly.", 2],
  ["vocab-survival", "What mattered was the outcome.", 1],
  ["vocab-survival", "Surviving the migration was the goal.", 1],
  ["vocab-survival", "The survivors of the outage were few.", 0],
  ["vocab-stance-2", "It is genuinely and deliberately different.", 2],
  ["vocab-stance-2", "She quietly left, plainly upset.", 2],
  ["vocab-stance-2", "To be honest, it was fine.", 1],
  ["vocab-stance-2", "The door was closed.", 0],
  ["vocab-metaphor-2", "The performance ceiling and the cost floor both moved.", 2],
  ["vocab-metaphor-2", "A sibling module and a twin PR.", 2],
  ["vocab-metaphor-2", "The lone ratchet in the toolkit.", 2],
  ["vocab-metaphor-2", "The room was wooden.", 0],
  ["vocab-survival-2", "The issue persisted, and the fix is proven.", 2],
  ["vocab-survival-2", "That settles it.", 1],
  ["vocab-survival-2", "He proved the theorem.", 0],
  ["not-just", "This is not just a tool, but a philosophy.", 1],
  ["not-just", "Not only fast but also reliable.", 1],
  ["not-just", "It’s not a bug — it’s a feature.", 1],
  ["not-just", "He did not buy it.", 0],
  ["not-just", "She was not sure about the plan.", 0],
  ["note-that", "It is important to note that timing matters.", 1],
  ["note-that", "It’s worth noting the fees are separate.", 1],
  ["note-that", "It should be noted that this changed in 2020.", 1],
  ["note-that", "It's worth pausing on that number.", 1],
  ["note-that", "It is worth asking who benefits.", 1],
  ["note-that", "Please note the door code.", 0],
  ["testament", "The building stands as a testament to postwar optimism.", 1],
  ["testament", "Her career is a testament to persistence.", 1],
  ["testament", "It serves as a stark reminder that nothing lasts.", 1],
  ["testament", "He read from the Old Testament.", 0],
  ["crucial-role", "Volunteers play a crucial role in the program.", 1],
  ["crucial-role", "She played a truly pivotal role in the merger.", 1],
  ["crucial-role", "He plays the role of the villain.", 0],
  ["landscape", "Adapting to an ever-evolving landscape.", 1],
  ["landscape", "The rapidly changing landscape of retail.", 1],
  ["landscape", "In today’s fast-paced world, attention is scarce.", 1],
  ["landscape", "The landscape outside the window was gray.", 0],
  ["vague-experts", "Experts argue that the policy failed.", 1],
  ["vague-experts", "Some critics have noted a decline in quality.", 1],
  ["vague-experts", "Industry reports suggest strong demand.", 1],
  ["vague-experts", "Dr. Chen argued the opposite in her paper.", 0],
  ["despite-challenges", "Despite these challenges, growth continued.", 1],
  ["despite-challenges", "The sector faces several challenges.", 1],
  ["despite-challenges", "Whether it works remains to be seen.", 1],
  ["despite-challenges", "Only time will tell whether it sticks.", 1],
  ["despite-challenges", "Time will tell.", 1],
  ["despite-challenges", "He arrived on time and will tell you himself.", 0],
  ["despite-challenges", "The climb was a challenge.", 0],
  [
    "participle-tail",
    "The bridge reopened in June, highlighting the city’s investment in infrastructure.",
    1,
  ],
  ["participle-tail", "Sales doubled, underscoring the strength of the brand.", 1],
  ["participle-tail", "She kept highlighting passages in yellow.", 0],
  ["participle-tail", "The team, reflecting on the loss, regrouped.", 0],
  ["promo", "The inn is nestled in a quiet valley.", 1],
  ["promo", "The museum boasts a rich tapestry of exhibits.", 2],
  ["promo", "Located in the heart of downtown.", 1],
  ["promo", "A hidden gem with breathtaking views.", 2],
  ["promo", "The soup was rich and hearty.", 0],
  ["ai-leftovers", "As of my last update, the API was in beta.", 1],
  ["ai-leftovers", "As an AI language model, I cannot form opinions.", 1],
  ["ai-leftovers", "See example.com/page?utm_source=chatgpt.com for details.", 1],
  ["ai-leftovers", "contentReference[oaicite:0]{index=0}", 2],
  ["ai-leftovers", "The last update shipped on Tuesday.", 0],
];

function truncate(s: string): string {
  const clean = s.replace(/\s+/g, " ").trim();
  return clean.length > 44 ? `${clean.slice(0, 41)}\u2026` : clean;
}

for (const [id, sample, expectMatches, expectCounts] of cases) {
  test(`${id} \u00b7 \u201c${truncate(sample)}\u201d`, () => {
    const rule = rules.find((r) => r.id === id);
    assert.ok(rule, `unknown rule: ${id}`);
    const found = rule.find(sample);
    assert.equal(found.length, expectMatches, "match count");
    if (expectCounts) {
      assert.deepEqual(
        found.map((f) => f.count),
        expectCounts,
        "item counts",
      );
    }
  });
}
