export default {
  mutate: [
    "compaction-visibility.ts",
    "configuration.ts",
    "edit-diff-stat.ts",
    "fold-policy.ts",
    "history-entry.ts",
    "history-index.ts",
    "history-input.ts",
    "history-navigation.ts",
    "history-renderer.ts",
    "history-scope.ts",
    "history-search.ts",
    "history-viewport.ts",
    "projection-plan.ts",
    "restart-marker.ts",
    "run-boundary.ts",
    "transcript-window-adapter.ts",
    "transcript-windows.ts",
    "tool-padding.ts",
    "turn-visibility.ts",
  ],
  testRunner: "vitest",
  checkers: ["typescript"],
  tsconfigFile: "tsconfig.json",
  coverageAnalysis: "perTest",
  thresholds: {
    high: 90,
    low: 85,
    break: 85,
  },
  reporters: ["clear-text", "progress"],
  tempDirName: ".stryker-tmp",
  vitest: {
    configFile: "vitest.config.ts",
  },
};
